# Trabajo Preparacion, visualizacion de Datos y Machine learning con Python<a class="tocSkip">
## Ciencia de datos en Produccion <a class="tocSkip">

**Estudiante:** Robert Garcia Rey

**ID:** 1094905142

**Email:** regarciar@unal.edu.co

 
**Ponga su nombre en el archivo de Jupyter Notebook 
Docente: [Jose R. Zapata](https://joserzapata.github.io)
- https://joserzapata.github.io
- https://twitter.com/joserzapata
- https://www.linkedin.com/in/jose-ricardo-zapata-gonzalez/       


<h1>Contenido<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Definir-el-Problema-a-Resolver" data-toc-modified-id="Definir-el-Problema-a-Resolver-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Definir el Problema a Resolver</a></span><ul class="toc-item"><li><span><a href="#Describir-los-datos-de-entrada-y-salida" data-toc-modified-id="Describir-los-datos-de-entrada-y-salida-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Describir los datos de entrada y salida</a></span></li></ul></li><li><span><a href="#Importar-Librerias" data-toc-modified-id="Importar-Librerias-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Importar Librerias</a></span></li><li><span><a href="#Cargar-Datasets" data-toc-modified-id="Cargar-Datasets-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Cargar Datasets</a></span></li><li><span><a href="#Descripcion--y-Limpieza-de-los-datos" data-toc-modified-id="Descripcion--y-Limpieza-de-los-datos-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Descripcion  y Limpieza de los datos</a></span><ul class="toc-item"><li><span><a href="#Identificacion-de-Variables" data-toc-modified-id="Identificacion-de-Variables-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Identificacion de Variables</a></span></li><li><span><a href="#Analisis-General-Univariable-y-Bivariable" data-toc-modified-id="Analisis-General-Univariable-y-Bivariable-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Analisis General Univariable y Bivariable</a></span></li><li><span><a href="#Eliminar-columnas-de-datos-Innecesarios" data-toc-modified-id="Eliminar-columnas-de-datos-Innecesarios-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Eliminar columnas de datos Innecesarios</a></span></li><li><span><a href="#Remover-Datos-Duplicados-Exactos" data-toc-modified-id="Remover-Datos-Duplicados-Exactos-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Remover Datos Duplicados Exactos</a></span></li><li><span><a href="#Procesamiento-de-Datos-Faltantes" data-toc-modified-id="Procesamiento-de-Datos-Faltantes-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Procesamiento de Datos Faltantes</a></span><ul class="toc-item"><li><span><a href="#Borrar-Filas" data-toc-modified-id="Borrar-Filas-4.5.1"><span class="toc-item-num">4.5.1&nbsp;&nbsp;</span>Borrar Filas</a></span></li><li><span><a href="#Reemplazar-datos-faltantes-con-la-Media/-Moda/-Mediana-(Mean/-Mode/-Median-Imputation)" data-toc-modified-id="Reemplazar-datos-faltantes-con-la-Media/-Moda/-Mediana-(Mean/-Mode/-Median-Imputation)-4.5.2"><span class="toc-item-num">4.5.2&nbsp;&nbsp;</span>Reemplazar datos faltantes con la Media/ Moda/ Mediana (Mean/ Mode/ Median Imputation)</a></span></li></ul></li><li><span><a href="#Remover-Datos-Duplicados-Exactos" data-toc-modified-id="Remover-Datos-Duplicados-Exactos-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Remover Datos Duplicados Exactos</a></span></li><li><span><a href="#Analisis-Univariable" data-toc-modified-id="Analisis-Univariable-4.7"><span class="toc-item-num">4.7&nbsp;&nbsp;</span>Analisis Univariable</a></span><ul class="toc-item"><li><span><a href="#Variables-Numericas" data-toc-modified-id="Variables-Numericas-4.7.1"><span class="toc-item-num">4.7.1&nbsp;&nbsp;</span>Variables Numericas</a></span></li><li><span><a href="#Variables-Categoricas" data-toc-modified-id="Variables-Categoricas-4.7.2"><span class="toc-item-num">4.7.2&nbsp;&nbsp;</span>Variables Categoricas</a></span></li></ul></li><li><span><a href="#Analisis-Bivariable" data-toc-modified-id="Analisis-Bivariable-4.8"><span class="toc-item-num">4.8&nbsp;&nbsp;</span>Analisis Bivariable</a></span><ul class="toc-item"><li><span><a href="#Numericas-vs-Numericas" data-toc-modified-id="Numericas-vs-Numericas-4.8.1"><span class="toc-item-num">4.8.1&nbsp;&nbsp;</span>Numericas vs Numericas</a></span></li><li><span><a href="#Categoricas-vs-Categoricas" data-toc-modified-id="Categoricas-vs-Categoricas-4.8.2"><span class="toc-item-num">4.8.2&nbsp;&nbsp;</span>Categoricas vs Categoricas</a></span></li><li><span><a href="#Categoricas-vs-Numericas" data-toc-modified-id="Categoricas-vs-Numericas-4.8.3"><span class="toc-item-num">4.8.3&nbsp;&nbsp;</span>Categoricas vs Numericas</a></span></li></ul></li><li><span><a href="#Procesamiento-de-Outliers" data-toc-modified-id="Procesamiento-de-Outliers-4.9"><span class="toc-item-num">4.9&nbsp;&nbsp;</span>Procesamiento de Outliers</a></span><ul class="toc-item"><li><span><a href="#Deteccion-de-Outliers-(Univariables-y-Bi-variables)" data-toc-modified-id="Deteccion-de-Outliers-(Univariables-y-Bi-variables)-4.9.1"><span class="toc-item-num">4.9.1&nbsp;&nbsp;</span>Deteccion de Outliers (Univariables y Bi variables)</a></span></li><li><span><a href="#Remover-Outliers" data-toc-modified-id="Remover-Outliers-4.9.2"><span class="toc-item-num">4.9.2&nbsp;&nbsp;</span>Remover Outliers</a></span></li></ul></li><li><span><a href="#Procesamiento-de-Outliers" data-toc-modified-id="Procesamiento-de-Outliers-4.10"><span class="toc-item-num">4.10&nbsp;&nbsp;</span>Procesamiento de Outliers</a></span><ul class="toc-item"><li><span><a href="#Deteccion-de-Outliers-(Univariables-y-Bi-variables)" data-toc-modified-id="Deteccion-de-Outliers-(Univariables-y-Bi-variables)-4.10.1"><span class="toc-item-num">4.10.1&nbsp;&nbsp;</span>Deteccion de Outliers (Univariables y Bi variables)</a></span></li><li><span><a href="#Remover-Outliers" data-toc-modified-id="Remover-Outliers-4.10.2"><span class="toc-item-num">4.10.2&nbsp;&nbsp;</span>Remover Outliers</a></span></li></ul></li><li><span><a href="#Feature-Engineering" data-toc-modified-id="Feature-Engineering-4.11"><span class="toc-item-num">4.11&nbsp;&nbsp;</span>Feature Engineering</a></span><ul class="toc-item"><li><span><a href="#Transformacion-de-Variables" data-toc-modified-id="Transformacion-de-Variables-4.11.1"><span class="toc-item-num">4.11.1&nbsp;&nbsp;</span>Transformacion de Variables</a></span><ul class="toc-item"><li><span><a href="#Normalizacion" data-toc-modified-id="Normalizacion-4.11.1.1"><span class="toc-item-num">4.11.1.1&nbsp;&nbsp;</span>Normalizacion</a></span></li><li><span><a href="#Escalamiento" data-toc-modified-id="Escalamiento-4.11.1.2"><span class="toc-item-num">4.11.1.2&nbsp;&nbsp;</span>Escalamiento</a></span></li><li><span><a href="#Logaritmica" data-toc-modified-id="Logaritmica-4.11.1.3"><span class="toc-item-num">4.11.1.3&nbsp;&nbsp;</span>Logaritmica</a></span></li><li><span><a href="#raíz-cuadrada-/-cúbica" data-toc-modified-id="raíz-cuadrada-/-cúbica-4.11.1.4"><span class="toc-item-num">4.11.1.4&nbsp;&nbsp;</span>raíz cuadrada / cúbica</a></span></li><li><span><a href="#Binning-,-Cambios-de-Numericas-a-Categoricas" data-toc-modified-id="Binning-,-Cambios-de-Numericas-a-Categoricas-4.11.1.5"><span class="toc-item-num">4.11.1.5&nbsp;&nbsp;</span>Binning , Cambios de Numericas a Categoricas</a></span></li></ul></li></ul></li><li><span><a href="#Analisis-Univariable-y-Bivariable-Final" data-toc-modified-id="Analisis-Univariable-y-Bivariable-Final-4.12"><span class="toc-item-num">4.12&nbsp;&nbsp;</span>Analisis Univariable y Bivariable Final</a></span><ul class="toc-item"><li><span><a href="#Creacion-de-Variables" data-toc-modified-id="Creacion-de-Variables-4.12.1"><span class="toc-item-num">4.12.1&nbsp;&nbsp;</span>Creacion de Variables</a></span><ul class="toc-item"><li><span><a href="#Crear-Variables-derivadas-de-Otras" data-toc-modified-id="Crear-Variables-derivadas-de-Otras-4.12.1.1"><span class="toc-item-num">4.12.1.1&nbsp;&nbsp;</span>Crear Variables derivadas de Otras</a></span></li><li><span><a href="#Crear-Variables-de-Categorico-a-Numerico" data-toc-modified-id="Crear-Variables-de-Categorico-a-Numerico-4.12.1.2"><span class="toc-item-num">4.12.1.2&nbsp;&nbsp;</span>Crear Variables de Categorico a Numerico</a></span></li></ul></li></ul></li><li><span><a href="#Reduccion-de-Dimensionalidad-y-Seleccion-de-Variables-(PCA)" data-toc-modified-id="Reduccion-de-Dimensionalidad-y-Seleccion-de-Variables-(PCA)-4.13"><span class="toc-item-num">4.13&nbsp;&nbsp;</span>Reduccion de Dimensionalidad y Seleccion de Variables (PCA)</a></span></li><li><span><a href="#Balance-de-datos" data-toc-modified-id="Balance-de-datos-4.14"><span class="toc-item-num">4.14&nbsp;&nbsp;</span>Balance de datos</a></span></li></ul></li><li><span><a href="#MODELAMIENTO-DE-LOS-DATOS-(MACHINE-LEARNING)" data-toc-modified-id="MODELAMIENTO-DE-LOS-DATOS-(MACHINE-LEARNING)-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>MODELAMIENTO DE LOS DATOS (MACHINE LEARNING)</a></span><ul class="toc-item"><li><span><a href="#Dividir-el-dataset-en-Training-set-y-Test-set" data-toc-modified-id="Dividir-el-dataset-en-Training-set-y-Test-set-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Dividir el dataset en Training set y Test set</a></span></li></ul></li><li><span><a href="#Validacion-y-Evaluacion-Cruzada-(k-fold-Cross-Validation)" data-toc-modified-id="Validacion-y-Evaluacion-Cruzada-(k-fold-Cross-Validation)-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Validacion y Evaluacion Cruzada (k-fold Cross Validation)</a></span></li><li><span><a href="#Optimizacion-de-Hiper-parametros-(Hyper-Parameter-optimization)" data-toc-modified-id="Optimizacion-de-Hiper-parametros-(Hyper-Parameter-optimization)-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Optimizacion de Hiper parametros (Hyper Parameter optimization)</a></span></li><li><span><a href="#Evaluacion-final-del-modelo-con-el-Test-set" data-toc-modified-id="Evaluacion-final-del-modelo-con-el-Test-set-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Evaluacion final del modelo con el Test set</a></span></li><li><span><a href="#Implementacion-del-Modelo-(Deploying)" data-toc-modified-id="Implementacion-del-Modelo-(Deploying)-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Implementacion del Modelo (Deploying)</a></span></li><li><span><a href="#Comunicacion-de-Resultados-(Data-Story-Telling)" data-toc-modified-id="Comunicacion-de-Resultados-(Data-Story-Telling)-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Comunicacion de Resultados (Data Story Telling)</a></span></li><li><span><a href="#Conclusiones" data-toc-modified-id="Conclusiones-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Conclusiones</a></span></li><li><span><a href="#Ayudas-Y-Referencias" data-toc-modified-id="Ayudas-Y-Referencias-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Ayudas Y Referencias</a></span></li></ul></div>

## Objetivo del Trabajo <a class="tocSkip">
El objetivo inicial del trabajo es utilizar Python para el procesamiento, descripcion  y visualización de datos, con el fin de dejar los datos preparados para ser usados con algoritmos de Machine Learning para Regresión o Clasificación como objetivo final del trabajo.

El trabajo se realizara en Python usando un jupyter notebook, llenando los campos de este archivo y subirlo a github.

## Las actividades a realizar<a class="tocSkip">
    
    
1) Preparar los datos, hacer cada uno de los pasos solo si es necesario:
      
    - Poner los datos en sus tipos de datos correctos
    - Remover los valores duplicados
    - Procesar y Reemplazar los datos que faltan (Missing N.A values)
    - Manejo de outliers
    - Re-escalar las variables
    - Normalizar
    - Data Binning
        - Conversión Numérico a categórico
        - Conversión Categórico a Numérico

2) Realizar una exploración estadística y con visualización de los datos
    - Scatter plots
    - Histogramas
    - boxplot, o las gráficas que considere necesarias


3) Entrene y Evalue modelos de Machine Learning según sea su problema, recuerde usar k-fold cross-validation para evitar over fitting, algunos algoritmos recomendados

    (a) PREDICCIÓN:
    
            ▪ Regresión Lineal
            ▪ Lasso
            ▪ Ridge
            ▪ Decision Tree regressor
            ▪ Random Forest regressor
            ▪ SVR
            ▪ KNR
            ▪ catboost regressor
            
    
    
    (b) CLASIFICACION
      
            ▪ Regresión Logística
            ▪ LinearSVC
            ▪ KernelSVC
            ▪ Decision Tree clasifier
            ▪ Random Forest classifier
            ▪ K-NN
            ▪ GaussianNB
            ▪ catboost
    
**Nota: utilizar visualizaciones para comunicar los resultados obtenidos.**    
            
4) Realizar hyperparameter optimization  de los dos métodos que tengan mejor resultado en los pasos anteriores para mejorar el desempeño obtenido. (Tenga en cuenta, que realizar el hyperparameter tuning no garantiza una mejora significativa en el desempeño, pero es bueno intentarlo)
    
5) Realizar comentarios de cada paso que va realizando en el documento y finalmente también agregue **conclusiones** de:
    
    - los datos procesados
    - la información que observa
    - Comparación de la evaluación de los Métodos
    - Cual fue el mejor modelo que obtuvo luego de la hiper parametrización
    
    
*NOTA: No dude en contactarme para cualquier pregunta o inquietud :)

## FORMATO DE ENTREGA  <a class="tocSkip">

EL jupyter notebook estara alojado en un repositorio de Github

El código debe tener comentarios y explicaciones de la solución del trabajo.


## EVALUACION <a class="tocSkip">
(33 % ) preparacion, descripcion y visualizacion de datos
    
(33 % ) Machine Learning, hiperparametrizacion y Conclusiones
    

|Porcentaje en la evaluación | Descripción| Nada | Incompleto | Completo |
| :---: |:---: |:---: |:---: |:---: |
| 11 % |**Preparación de los datos** <br> (datos nulos, outliers, duplicados, <br> corrección de formatos de tipos de datos) |
|11 % | **Visualización de datos** <br> (Univarible y Bivariable) <br> Histogramas, boxplots, correlaciones, etc|
|11 % | **Descripción y Análisis Estadístico de los datos** |
|11 % | **Machine Learning** <br> Entrenar y evaluar todos los modelos propuestos |
|11 % | **Hiper parametrizacion** <br> Hiperparametrizar 2 modelos y escoger el mejor modelo |   
|11 % | **Resultados y Conclusiones** <br> analisis de los datos, conclusiones del modelos y los resultados obtenidos|


Ejemplos y links de ayuda al final del documento

# Definir el Problema a Resolver

Determinar  automaticamente si un pacciente tiene problemas de corazon basado en los datos de sus examenes.

## Describir los datos de entrada y salida
- Cantidad de Variables
- Tipo de Variables
- Significado de cada Variable

# Importar Librerias

In [1]:
import pandas as pd
pd.options.plotting.backend = "plotly"
import numpy as np

# Cargar Datasets

In [140]:
data_raw = pd.read_csv("../data/raw/corazonDS.csv")

# Descripcion General del Dataset
- numero de filas y columnas
- tipos de datos y si estan correctos

In [141]:
data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90900 entries, 0 to 90899
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  90900 non-null  int64 
 1   index       90900 non-null  int64 
 2   ca          83750 non-null  object
 3   exang       84175 non-null  object
 4   old_peak    84050 non-null  object
 5   lokij       90900 non-null  int64 
 6   sex         86400 non-null  object
 7   chol        85745 non-null  object
 8   rest_ecg    83095 non-null  object
 9   thal        84590 non-null  object
 10  disease     85225 non-null  object
 11  gyuhi       84175 non-null  object
 12  rest_bp     86060 non-null  object
 13  age         86975 non-null  object
 14  max_hr      83615 non-null  object
 15  slope       84065 non-null  object
 16  chest_pain  85560 non-null  object
 17  fbs         85320 non-null  object
dtypes: int64(3), object(15)
memory usage: 12.5+ MB


In [142]:
data_raw.head()

Unnamed: 0  index   ca exang old_peak  lokij                  sex  \
0           0   1823  0.0     0      0.8  34567         123654985132   
1           1    921  NaN   NaN      NaN  34567  gtyubhjnk 76t38whyu   
2           2   2820  0.0     0      0.6  34567                  NaN   
3           3   2299  1.0     0      1.9  34567                 Male   
4           4   2239  3.0     1      1.8  34567                 Male   

                  chol                       rest_ecg                 thal  \
0         123654985132                         normal               normal   
1  gtyubhjnk 76t38whyu                            NaN  gtyubhjnk 76t38whyu   
2                  141                         normal               normal   
3                  315                         normal        -365489651984   
4                  330  left ventricular hypertrophy            reversable   

               disease gyuhi rest_bp  age max_hr slope     chest_pain  fbs  
0         123654985132     0     120   56    178     1     nontypical  0.0  
1  gtyubhjnk 76t38whyu   NaN     130   56    NaN   NaN     nonanginal  1.0  
2                    0     0     NaN   44    175     2            NaN  NaN  
3                    0     0     130   43    162     1  -365489651984  0.0  
4                    1     1     130  NaN    132   NaN   asymptomatic  1.0

# Limpieza de calidad de datos general

- Filas con valores exactamente iguales (duplicados) <br>
Se comprueba si el mismo paciente tiene más de un encuentro.

In [143]:
data_raw["index"].duplicated().sum()

87870

Eliminar pacientes duplicados

In [144]:
data_raw.drop_duplicates(subset ="index", inplace = True)

In [145]:
data_raw["index"].duplicated().sum()

0

In [146]:
data_raw

Unnamed: 0  index   ca exang old_peak  lokij                  sex  \
0               0   1823  0.0     0      0.8  34567         123654985132   
1               1    921  NaN   NaN      NaN  34567  gtyubhjnk 76t38whyu   
2               2   2820  0.0     0      0.6  34567                  NaN   
3               3   2299  1.0     0      1.9  34567                 Male   
4               4   2239  3.0     1      1.8  34567                 Male   
...           ...    ...  ...   ...      ...    ...                  ...   
12031       12031   1479  NaN   NaN      NaN  34567                 Male   
12383       12383    583  NaN     1      3.0  34567                 Male   
12547       12547   2571  0.0     0      0.0  34567                 Male   
12860       12860   2387  0.0  xxxx      1.0  34567                 Male   
13549       13549   2606  2.0     0     xxxx  34567                 Male   

                      chol                       rest_ecg  \
0             123654985132                         normal   
1      gtyubhjnk 76t38whyu                            NaN   
2                      141                         normal   
3                      315                         normal   
4                      330  left ventricular hypertrophy    
...                    ...                            ...   
12031         123654985132                            NaN   
12383                  NaN                         normal   
12547                  250                         normal   
12860                  204                         normal   
13549                  244  left ventricular hypertrophy    

                      thal              disease gyuhi       rest_bp  age  \
0                   normal         123654985132     0           120   56   
1      gtyubhjnk 76t38whyu  gtyubhjnk 76t38whyu   NaN           130   56   
2                   normal                    0     0           NaN   44   
3            -365489651984                    0     0           130   43   
4               reversable                    1     1           130  NaN   
...                    ...                  ...   ...           ...  ...   
12031                  NaN                    1   NaN  123654985132   59   
12383           reversable                    1     1           110   57   
12547               normal                    0     0           112   41   
12860                  NaN                    1  xxxx           128   52   
13549                 xxxx                    0     0           148   42   

             max_hr slope     chest_pain  fbs  
0               178     1     nontypical  0.0  
1               NaN   NaN     nonanginal  1.0  
2               175     2            NaN  NaN  
3               162     1  -365489651984  0.0  
4               132   NaN   asymptomatic  1.0  
...             ...   ...            ...  ...  
12031  123654985132   NaN   123654985132  1.0  
12383           143     2            NaN  NaN  
12547           179     1     nonanginal  NaN  
12860           156     2           xxxx  1.0  
13549           178     1        typical  0.0  

[3030 rows x 18 columns]

Remover Columnas innecesarias

In [147]:
data_raw.drop(['Unnamed: 0','index', 'lokij', 'gyuhi'],axis=1,inplace=True)

- Columnas duplicadas después de eliminar columnas innecesarias

In [148]:
print(f"Duplicated data = {len(data_raw)-len(data_raw.drop_duplicates())}")

Duplicated data = 296


- Columnas con valores constantes o sin informacion

In [149]:
data_raw.sample(14).T

4552        1353                           2986  \
ca                   0.0         1.0                            0.0   
exang       123654985132           0                   123654985132   
old_peak             0.0         0.6                            2.5   
sex                 Male        Male                           Male   
chol        123654985132         233                            177   
rest_ecg          normal      normal  left ventricular hypertrophy    
thal              normal  reversable                   123654985132   
disease                0           1                   123654985132   
rest_bp              120         140                            120   
age         123654985132          50                             43   
max_hr               169         163                   123654985132   
slope       123654985132           2                              2   
chest_pain    nontypical  nonanginal                   asymptomatic   
fbs                  0.0         0.0                            0.0   

                    604                            468         1513  \
ca                   1.0                            0.0         NaN   
exang                  1                              0           1   
old_peak             2.8                            1.3         0.1   
sex                 Male                         Female        Male   
chol                 239                            294         247   
rest_ecg          normal  left ventricular hypertrophy         xxxx   
thal          reversable                         normal  reversable   
disease                1                              0           1   
rest_bp              110                            140         132   
age                   54                            NaN        xxxx   
max_hr               126                            NaN         143   
slope                  2                              2           2   
chest_pain  asymptomatic                     nontypical        xxxx   
fbs                  0.0                            NaN         1.0   

                  970           9175                           540   \
ca                 1.0           0.0                            0.0   
exang                0             1                              1   
old_peak           0.0           5.6                           xxxx   
sex             Female          Male                           Male   
chol               198           217                            177   
rest_ecg        normal        normal  left ventricular hypertrophy    
thal            normal    reversable                     reversable   
disease              0             1                              1   
rest_bp            105           140                            120   
age                 41            55                           xxxx   
max_hr             168           111                           xxxx   
slope                1             3                              2   
chest_pain  nontypical  asymptomatic                           xxxx   
fbs                0.0           0.0                            0.0   

                  2216                           1385  \
ca                 1.0                            0.0   
exang                0                           xxxx   
old_peak           0.0                            0.6   
sex               xxxx                         Female   
chol               198                            295   
rest_ecg        normal  left ventricular hypertrophy    
thal              xxxx                         normal   
disease              0                              0   
rest_bp            105                            120   
age                 41                           xxxx   
max_hr             168                            157   
slope                1                              1   
chest_pain  nontypical                     nonanginal   
fbs                0.0  

In [150]:
for col in data_raw:
    print(f"{col} = {data_raw[col].unique()}")

ca = ['0.0' nan '1.0' '3.0' '-365489651984' 'xxxx' '2.0' 'gtyubhjnk 76t38whyu'
 '123654985132' 'afd']
exang = ['0' nan '1' '-365489651984' 'xxxx' 'gtyubhjnk 76t38whyu' '123654985132'
 'f' 'adfs']
old_peak = ['0.8' nan '0.6' '1.9' '1.8' '-365489651984' '0.0' '2.8' 'xxxx' '1.0'
 'gtyubhjnk 76t38whyu' '0.2' '4.0' '2.6' '1.5' '1.2' '6.2' '1.6' '3.2'
 '123654985132' '2.0' '4.4' '3.4' '0.4' '0.3' '2.3' '1.4' '3.0' '2.5'
 '0.1' '0.9' '2.4' '2.2' '0.5' '3.6' '4.2' '1.3' '1.1' '2.1' '3.8' '2.9'
 '0.7' '5.6' '3.1' '3.5' 'asd' 'afd']
sex = ['123654985132' 'gtyubhjnk 76t38whyu' nan 'Male' 'Female' 'xxxx'
 '-365489651984' '45' '2345' '765']
chol = ['123654985132' 'gtyubhjnk 76t38whyu' '141' '315' '330' '313' '221' '252'
 '-365489651984' '319' '304' '225' '182' '149' '263' '175' '283' '274'
 '289' '256' '180' '227' '284' '206' '223' '213' '187' '321' '234' nan
 '174' '196' '286' '254' '294' '245' '243' '264' '222' '325' '164' '262'
 '249' '209' '214' '219' '267' '275' '201' 'xxxx' '326' '318' '247' 

**Análisis**

* Todas las columnas tienen los siguientes valores: 'xxxx' 'gtyubhjnk 76t38whyu' '-365489651984.0'
 '123654985132.0' 'adfs' '-365489651984'<br> Por tanto se procede a reemplazar todos los errores de los datos con valores nan columna por columna

In [151]:
data_raw["ca"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', 'afd'], np.nan, inplace= True)
data_raw["exang"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', 'f', 'afds'], np.nan, inplace= True)
data_raw["old_peak"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', 'asd', 'afd'], np.nan, inplace= True)
data_raw["sex"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', '45', '2345', '765'], np.nan, inplace= True)
data_raw["chol"].replace(['-365489651984', 'gtyubhjnk 76t38whyu', '123654985132', 'wtey', 'sfdywe'], np.nan, inplace= True)
data_raw["rest_ecg"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', '36653', '5678', '435647', '3563'], np.nan, inplace= True)
data_raw["thal"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', '365635463', '87654'], np.nan, inplace= True)
data_raw["disease"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', 'gsfdg', 'sf', 'fsg', 'fsdg'], np.nan, inplace= True)
data_raw["rest_bp"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', 'fsgh', 'wety'], np.nan, inplace= True)
data_raw["age"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', 'fggfds', 'sdg'], np.nan, inplace= True)
data_raw["max_hr"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', 'adfs'], np.nan, inplace= True)
data_raw["slope"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', 'afd'], np.nan, inplace= True)
data_raw["chest_pain"].replace(['-365489651984', 'xxxx', 'gtyubhjnk 76t38whyu', '123654985132', '2345', '3456'], np.nan, inplace= True)
data_raw["fbs"].replace(['xxxx', 'gtyubhjnk 76t38whyu', '-365489651984.0', '123654985132.0'], np.nan, inplace= True)


In [153]:
for col in data_raw:
    print(f"{col} = {data_raw[col].unique()}")

ca = ['0.0' nan '1.0' '3.0' '2.0']
exang = ['0' nan '1' 'adfs']
old_peak = ['0.8' nan '0.6' '1.9' '1.8' '0.0' '2.8' '1.0' '0.2' '4.0' '2.6' '1.5'
 '1.2' '6.2' '1.6' '3.2' '2.0' '4.4' '3.4' '0.4' '0.3' '2.3' '1.4' '3.0'
 '2.5' '0.1' '0.9' '2.4' '2.2' '0.5' '3.6' '4.2' '1.3' '1.1' '2.1' '3.8'
 '2.9' '0.7' '5.6' '3.1' '3.5']
sex = [nan 'Male' 'Female']
chol = [nan '141' '315' '330' '313' '221' '252' '319' '304' '225' '182' '149'
 '263' '175' '283' '274' '289' '256' '180' '227' '284' '206' '223' '213'
 '187' '321' '234' '174' '196' '286' '254' '294' '245' '243' '264' '222'
 '325' '164' '262' '249' '209' '214' '219' '267' '275' '201' 'xxxx' '326'
 '318' '247' '303' '229' '261' '233' '305' '235' '308' '177' '244' '226'
 '257' '341' '335' '186' '394' '269' '220' '203' '302' '228' '255' '230'
 '282' '241' '204' '211' '200' '353' '248' '300' '192' '342' '239' '288'
 '197' '278' '265' '185' '340' '215' '216' '293' '258' '268' '217' '198'
 '270' '271' '166' '236' '281' '205' '409' '417' '207' '27

In [152]:
data_raw

ca exang old_peak   sex chol                       rest_ecg  \
0      0.0     0      0.8   NaN  NaN                         normal   
1      NaN   NaN      NaN   NaN  NaN                            NaN   
2      0.0     0      0.6   NaN  141                         normal   
3      1.0     0      1.9  Male  315                         normal   
4      3.0     1      1.8  Male  330  left ventricular hypertrophy    
...    ...   ...      ...   ...  ...                            ...   
12031  NaN   NaN      NaN  Male  NaN                            NaN   
12383  NaN     1      3.0  Male  NaN                         normal   
12547  0.0     0      0.0  Male  250                         normal   
12860  0.0   NaN      1.0  Male  204                         normal   
13549  2.0     0      NaN  Male  244  left ventricular hypertrophy    

             thal disease rest_bp  age max_hr slope    chest_pain  fbs  
0          normal     NaN     120   56    178     1    nontypical  0.0  
1             NaN     NaN     130   56    NaN   NaN    nonanginal  1.0  
2          normal       0     NaN   44    175     2           NaN  NaN  
3             NaN       0     130   43    162     1           NaN  0.0  
4      reversable       1     130  NaN    132   NaN  asymptomatic  1.0  
...           ...     ...     ...  ...    ...   ...           ...  ...  
12031         NaN       1     NaN   59    NaN   NaN           NaN  1.0  
12383  reversable       1     110   57    143     2           NaN  NaN  
12547      normal       0     112   41    179     1    nonanginal  NaN  
12860         NaN       1     128   52    156     2           NaN  1.0  
13549         NaN       0     148   42    178     1       typical  0.0  

[3030 rows x 14 columns]

In [159]:
(data_raw.isnull().sum()*100/len(data_raw)).plot.bar(title = 'Percentage of Missing Values per column',color=data_raw.columns)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'hovertemplate': 'color=ca<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'ca',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': 'ca',
              'offsetgroup': 'ca',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['ca'], dtype=object),
              'xaxis': 'x',
              'y': array([22.44224422]),
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'color=exang<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'exang',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': 'exang',
              'offsetgroup': 'exang',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['exang'], dtype=object),
              'xaxis': 'x',
              'y': array([20.56105611]),
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'color=old_peak<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'old_peak',
              'marker': {'color': '#00cc96', 'pattern': {'shape': ''}},
              'name': 'old_peak',
              'offsetgroup': 'old_peak',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['old_peak'], dtype=object),
              'xaxis': 'x',
              'y': array([20.59405941]),
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'color=sex<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'sex',
              'marker': {'color': '#ab63fa', 'pattern': {'shape': ''}},
              'name': 'sex',
              'offsetgroup': 'sex',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['sex'], dtype=object),
              'xaxis': 'x',
              'y': array([18.81188119]),
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'color=chol<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'chol',
              'marker': {'color': '#FFA15A', 'pattern': {'shape': ''}},
              'name': 'chol',
              'offsetgroup': 'chol',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['chol'], dtype=object),
              'xaxis': 'x',
              'y': array([14.09240924]),
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'color=rest_ecg<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'rest_ecg',
              'marker': {'color': '#19d3f3', 'pattern': {'shape': ''}},
              'name': 'rest_ecg',
              'offsetgroup': 'rest_ecg',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['rest_ecg'], dtype=object),
              'xaxis': 'x',
              'y': array([21.45214521]),
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'color=thal<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'thal',
              'marker': {'color': '#FF6692', 'pattern': {'shape': ''}},
              'name': 'thal',
              'offsetgroup': 'thal',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',


In [161]:
missing = data_raw.isnull().sum()
missing[missing>0]*100/len(data_raw)

ca            22.442244
exang         20.561056
old_peak      20.594059
sex           18.811881
chol          14.092409
rest_ecg      21.452145
thal          20.693069
disease       20.429043
rest_bp       18.778878
age           18.316832
max_hr        22.739274
slope         21.419142
chest_pain    19.669967
fbs           19.669967
dtype: float64

In [162]:
data_raw.isnull().sum()

ca            680
exang         623
old_peak      624
sex           570
chol          427
rest_ecg      650
thal          627
disease       619
rest_bp       569
age           555
max_hr        689
slope         649
chest_pain    596
fbs           596
dtype: int64

In [163]:
data_raw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3030 entries, 0 to 13549
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   ca          2350 non-null   object
 1   exang       2407 non-null   object
 2   old_peak    2406 non-null   object
 3   sex         2460 non-null   object
 4   chol        2603 non-null   object
 5   rest_ecg    2380 non-null   object
 6   thal        2403 non-null   object
 7   disease     2411 non-null   object
 8   rest_bp     2461 non-null   object
 9   age         2475 non-null   object
 10  max_hr      2341 non-null   object
 11  slope       2381 non-null   object
 12  chest_pain  2434 non-null   object
 13  fbs         2434 non-null   object
dtypes: object(14)
memory usage: 355.1+ KB


## Dividir el dataset en Training set y Test set

Este paso debe ser al inicio de los proyectos,  Se deben realizar todas las transformaciones, preparación de datos y limpieza de los datos, en el train set y en la evaluacion se deben aplicarl al test set y a los datos nuevos que lleguen al sistema. Esta division inicial se hace para evitar data leakage de los datos de test a los datos de train, por ejemplo en las imputaciones.

Por este motivo se realizara en esta parte.

Division de los datos de entrenamiento (Train set) y de Evaluacion (test - set), las divisiones utilizadas son

- 80% (train) , 20%(test)
- 70% (train) , 30%(test)

El **Train set** se hace para seleccion de Modelos y el **Test-set** solamente para la evaluacion Final

# Descripcion  y Limpieza de los datos

## Identificacion de Variables
- Variables de entrada y de salida
- Tipo de Variables (categoricas o Numericas)
- Tipo de datos (int, float, string, factor, boolean, ...)

## Analisis General Univariable y Bivariable 
Analisis de cada una de las variables para lograr calidad de datos en cada columna
- **Correccion del tipo de dato (numericas, categoricas, string) de cada columna (optimizar memoria)**
- Deteccion de numero de datos faltantes
- Deteccion de duplicados

## Eliminar columnas de datos Innecesarios

Analizar el problema a resolver e indentificar cuales variables no brindan informacion y borrarlas.

## Remover Datos Duplicados Exactos

Hacer al principio luego de cargar los datos y cada vez luego de Hacer imputaciones, eliminacion de columnas o registros.

## Procesamiento de Datos Faltantes
Las opciones que se pueden usar dependiendo del analisis de los datos son:
### Borrar Filas
- Borrar las filas que les falten todos los datos
- Borrar Solo las filas que les falta las variables mas importantes o la salida

### Reemplazar datos faltantes con la Media/ Moda/ Mediana (Mean/ Mode/ Median Imputation)
De necesitarse hacer imputacion se debe verificar los outliers para no cometer errores en la imputacion

## Remover Datos Duplicados Exactos

Hacer al principio luego de cargar los datos y cada vez luego de Hacer imputaciones, eliminacion de columnas o registros.

## Analisis Univariable

Estadistico Descriptico y Analisis

### Variables Numericas

Tendencia Central  | Medida de Dispersión  |  Visualizacion
 :---: | :---: | :---:
Media   | Rango      |  Histogramas
Mediana | Cuartiles  |  Boxplots
Moda    | Rango inter cuartil (IQR)|  
Minimo  | Varianza   |  
Maximo  | Desviacion Estandard | 
   .    | Skewness   |  
 .      | Kurtosis   |  

### Variables Categoricas
- Numero de elementos por categoria
- Porcentaje de elementos por categoria
- Graficos de barras

## Analisis Bivariable
Estadistico Descriptico y Analisis

### Numericas vs Numericas
- Scatter Plot
- Heatmap
- Correlacion

### Categoricas vs Categoricas

- Two-way table
- Graficas de Barras apiladas
- Chi-Square Test

### Categoricas vs Numericas
- Z-Test/ T-Test
- ANOVA

## Procesamiento de Outliers
### Deteccion de Outliers (Univariables y Bi variables)
- Boxplots
- Scatter Plots
- Histogramas

### Remover Outliers
las opciones son:
- Borrar los datos atipicos (outliers) 
- Transformar la variable (Ej: escalar, cambiar a esccala Log o a Escala lineal)
- Reemplazar los outliers conla Media/ Moda/ Mediana (Mean/ Mode/ Median Imputation)
- Reemplazar valores con modelo predictivo
- Separarlos y analizarlos aparte (si son muchos outliers)


## Procesamiento de Outliers
### Deteccion de Outliers (Univariables y Bi variables)
- Boxplots
- Scatter Plots
- Histogramas

### Remover Outliers
las opciones son:
- Borrar los datos atipicos (outliers) 
- Transformar la variable (Ej: escalar, cambiar a esccala Log o a Escala lineal)
- Reemplazar los outliers conla Media/ Moda/ Mediana (Mean/ Mode/ Median Imputation)
- Reemplazar valores con modelo predictivo
- Separarlos y analizarlos aparte (si son muchos outliers)


## Feature Engineering 
### Transformacion de Variables
**Se usa cuando es necesario:**
- Cambiar la escala las variables (Normalizar, escalamiento, etc), esto no cambia la forma de la distribucion de los datos
- Cambiar relaciones No ineales en Lineales (Ej: cambiar la escala Logaritmica a lineal)
- Usar una la distribución simétrica en vez de una distribución sesgada o asimetrica, Para una la distribución sesgada a la derecha, tomamos la raíz cuadrada / cúbica o el logaritmo de la variable, y para la desviación a la izquierda, tomamos el cuadrado / cubo o exponencial de las variables.
- Cambair variables continuas a categoricas

Algunas transformaciones son:

#### Normalizacion

#### Escalamiento

#### Logaritmica

#### raíz cuadrada / cúbica

#### Binning , Cambios de Numericas a Categoricas

## Analisis Univariable y Bivariable Final
Luego de Realizar:
- Tratamiento de datos Nulos
- Tratamiento de outliers
- Transformacion de Variables

Es necesario realizar nuevamente analisis univarible y bivariable para identificar como cambiaron nuestros datos y para verificar si estan listos para usarse para crear un modelo.

### Creacion de Variables
pueden ser:
#### Crear Variables derivadas de Otras

#### Crear Variables de Categorico a Numerico
Puede ser
- Definir un numero a cada categoria
- One hot encoder (dummy columns)

## Reduccion de Dimensionalidad y Seleccion de Variables (PCA)

De ser necesario si tiene muchas variables o sospecha que aun tiene variables que no aportan mucho

# MODELAMIENTO DE LOS DATOS (MACHINE LEARNING)


# Validacion y Evaluacion Cruzada (k-fold Cross Validation)

Se hace seleccion de los mejores modelos usando el Training Set y k-fold Cross Validation

# Optimizacion de Hiper parametros (Hyper Parameter optimization)

Se seleccionan solo los mejores modelos para realizar el ajuste de hiperparametros, ya que tiene una carga computacional alta.

Al final se obtienen los parametros del mejor modelo

# Evaluacion final del modelo con el Test set

Tomar los parametros obtenidos en el paso anterior, se crea el modelo con esos pararmetros y se entrena el modelo con todos los datos del **Train -set**

Finalmente se realiza la evaluacion (segun su problema si es de regresion o de clasificacion) usando el **Test - set** para definir si el modelo obtenido esta bien. Compare los resultados con el **Train -set** vs los resultados con el **Test - set**

# Implementacion del Modelo (Deploying)
Con el análisis básico y el ajuste hecho, comienza el trabajo real (ingeniería).

El último paso para poner en produccion el modelo de prediccion sera:
1. Entrenarlo en todo el conjunto de datos nuevamente, para hacer un uso completo de todos los datos disponibles. 
2. Usar los mejores parámetros encontrados mediante la validación cruzada, por supuesto. Esto es muy similar a lo que hicimos al principio, pero esta vez teniendo una idea de su comportamiento y estabilidad. La evaluación se realizó con honestidad, en divisiones distintas de entrenamiento / prueba.

El predictor final se puede serializar y grabar en el disco, de modo que la próxima vez que lo usemos, podemos omitir todo el entrenamiento y usar el modelo capacitado directamente:

In [132]:
#import pickle # Esta es una libreria de serializacion nativa de python, puede tener problemas de seguridad
from joblib import dump # libreria de serializacion

# garbar el modelo en un archivo
#dump(Modelo_final, 'Nombre_Archivo_Modelo.joblib')

# Comunicacion de Resultados (Data Story Telling)

# Conclusiones

# Ayudas Y Referencias

- https://medium.com/@joserzapata/paso-a-paso-en-un-proyecto-machine-learning-bcdd0939d387
- [Proyecto de Principio a Final sobre readmision de pacientes con Diabetes](https://github.com/JoseRZapata/Readmission-ML-Project)

- [a-complete-machine-learning-walk-through-in-python-part-one](https://towardsdatascience.com/a-complete-machine-learning-walk-through-in-python-part-one-c62152f39420)


- [a-starter-pack-to-exploratory-data-analysis-with-python-pandas-seaborn-and-scikit-learn](https://towardsdatascience.com/a-starter-pack-to-exploratory-data-analysis-with-python-pandas-seaborn-and-scikit-learn-a77889485baf#249d)

- [a-data-science-for-good-machine-learning-project-walk-through-in-python-part-one](https://towardsdatascience.com/a-data-science-for-good-machine-learning-project-walk-through-in-python-part-one-1977dd701dbc)

- [Ejemplos de Kaggle](https://www.kaggle.com/kernels?sortBy=hotness&group=everyone&pageSize=20&language=Python&kernelType=Notebook)

- [END to END ML from data colletion to deployment](https://medium.com/datadriveninvestor/end-to-end-machine-learning-from-data-collection-to-deployment-ce74f51ca203)

Docente: [Jose R. Zapata](https://joserzapata.github.io)
- https://joserzapata.github.io
- https://twitter.com/joserzapata
- https://www.linkedin.com/in/jose-ricardo-zapata-gonzalez/   